### ISSUE TITLE
svg displayed in a frame

### ISSUE THREAD

**Issue by fama** [restlessminded/dokuwiki-plugin-svgEmbed#4] opened 2020-01-16 22:35 UTC
Great plugin.  Thank you so much for the amazing work.

One of the issues, we found a problem with links:

1. you do workflow diagrams (in draw.io for example)
2. the diagrams container hyperlinks / URLs
3. and then you export the diagram into .svg and embed the svg into a dokuwiki page

When you click on the link, the link gets opened as if inside a frame, which ruins the usability of the links.  Any suggested workaround for this?

**Comment by restlessminded** [comment] 2020-01-16 22:47
I don't exactly follow.  Are you embedding Dokuwiki in an iframe or does your template have an iframe in it?

**Comment by restlessminded** [comment] 2020-01-16 22:52
Also, can you provide me with a sample file that exhibits this issue?

**Comment by fama** [comment] 2020-01-16 22:57
The link does not open in the main browser window.  Instead, the pages stays the same, but the link is opened in the area previously occupied by the embedded svg (as if it opened the link in an iframe).

We use heavily process diagrams in svg and wanted to link the boxes in the svg to pages in dokuwiki that explain the details.  But instead of opening the links in main browser, it opens them in the svg display area.

**Comment by restlessminded** [comment] 2020-01-16 22:59
I understand now, I think.  What browser and operating system?

**Comment by restlessminded** [comment] 2020-01-16 23:05
I did a quick Google and found this page that mirrors your experience:  https://stackoverflow.com/questions/7008355/how-to-make-links-in-an-embedded-svg-file-open-in-the-main-window-not-in-a-sepa

It sounds as though that would have to be rectified in the .svg file itself by setting a target, but I am doing some more checking to see if there's something I can set on the \<embed\> tag or in the stylesheet to force it to open in a different target.

**Comment by fama** [comment] 2020-01-16 23:05
OS:  Windows 10
Browsers tested:
Chromium 79.0.3945
Firefox: 72.0.1
Because it happens on all browser, it may be something else.
Template:  Bootstrap 3

**Comment by fama** [comment] 2020-01-16 23:14
Hmmm.  The draw.io does not let you construct the complete anchor.  You can only put a URL.

I still suspect, that it may be an issue in dokuwiki embedding. 

If I open the svg file 
mywiki.com/_media/folder/diagram.svg

and then click on the hyperlink, it opens the URL correctly on the main window (You can see the URL change to the new one in the browser window).  If it were problem with the .svg, the URL on the browser window should stay the same (mywiki.com/_media/folder/diagram.svg) and just display the content where the .svg was before.

**Comment by restlessminded** [comment] 2020-01-16 23:26
See my test page:  http://moria.megadungeon.org/wiki/wiki/sandbox

In the upper left of the .svg file you will see a red circle (in Chrome, or in Firefox you will just see a number '1') that's clickable and it goes to another page on the wiki.  Tell me how it opens it on your device (full screen, or embedded in the frame of the .svg object).

On my wiki and browsers, it opens the page in the full page.

Also, if you could provide me with an example .svg I could perhaps work out what the issue is.

**Comment by restlessminded** [comment] 2020-01-16 23:39
Actually, nix that.  I set **target="_top"** in the link.  If I remove it and then refresh the page I see the same issue you're having.  I also see there's a request with them at https://github.com/jgraph/drawio/issues/331 to set the target.

Let me do some tinkering.

**Comment by fama** [comment] 2020-01-16 23:44
Very interesting!!!   You nailed it!

Yes, right now it show "embedded" contents:
![image](https://user-images.githubusercontent.com/720793/72572280-ac427b80-3887-11ea-80d0-c5030fcb2397.png)

**Comment by restlessminded** [comment] 2020-01-17 00:37
Yes, that's from removing the **target="_top"** attribute from the link in my .svg file.  Since the file is embedded and can be from a plugin, there's no way (that I'm aware of, anyway) for the browser to reach into the .svg file and modify its behavior since the browser is just displaying the content according to the type that gets passed, so the undesired behavior is sort of by design.

I looked at \<embed\> and \<object\> and there are no attributes to force targets in the embedded content to open elsewhere (because it may be something like a video or some other source, it's under the control of the embedded media).  I tried them both with the **target="_top"** anyway, just to be sure and still no changes in functionality.

I do have a suggestion for you, though:

![svglinks](https://user-images.githubusercontent.com/52088098/72574461-c2076f00-388e-11ea-9546-b7dc3aa3f1fe.png)

When you export from [draw.io](http://draw.io) to .svg format, if you change **Links** to **Open in This Window** then the **target="_top"** attribute is set for all links in the document.  That would resolve your problem.

**Comment by restlessminded** [comment] 2020-01-17 17:20
Okay, one last-ditch, I loaded up the .svg file and embedded it directly into my page.  While that will solve the problem because the .svg is in the same document as the HTML so links will open full-page, you then have the problem of the .svg not scaling properly unless I directly rewrite the .svg.  I don't like that for a number of reasons:

1. I have to worry about the validity of the file, and the validity of my edits.
2. I don't want to change their data.  It can introduce new issues potentially.
3. It's a lot more complexity for something that should be simple (embedding an .svg file).
4. The wikipages and the edit pages will grow a lot because the .svg is directly embedded in the page.  It causes slower rendering times and will use a lot more storage on the server.

Since this can be resolved by properly setting targets in the .svg file I have to say that isn't a solution I am comfortable with.

**Closed** 2020-01-17 17:20 UTC
Labels: not a problem, wontfix

**Comment by restlessminded** [comment] 2020-01-21 20:13
@fama, were you able to save your files out of draw.io and with the correct target set?

**Comment by fama** [comment] 2020-01-21 23:58
@restlessminded :  The export in draw.io using "Open in New Window" worked perfectly.  Problem resolved!  Thank you so much for all the tips!
